<hr style="height:.9px;border:none;color:#333;background-color:#333;" />
<hr style="height:.9px;border:none;color:#333;background-color:#333;" />
<br><br><br><br><br>
<u><b><font size = 6>A2: Team Project OJ </f></b></u><br><br>
<b><font size = 5> Data Optimization - DAT-5304 </f></b>
<br><br>
<b>Authors</b>          : Carolina Novello Moreira, Jack Daoud & Max Lembke <br>
<b>Date Created</b> : 03/24/2021<br>
<br><br><br><br><br>
<hr style="height:.9px;border:none;color:#333;background-color:#333;" />
<hr style="height:.9px;border:none;color:#333;background-color:#333;" />
<br>


<b><font size = 5> Instructions </f></b>

This option involves using one of the two real-world datasets that I posted on Canvas. These datasets have information on Unit Sales, Prices, and Gross Margins for several SKU’s (Stock Keeping Units). The OJ Data is from Dominik’s Grocery Store in Chicago. The Milk Dataset is from Peru. Both have weekly data for multiple years. Using this data, you should advise management as to what they should do. Your advice could include marketing strategies (feature and display in OJ Dataset or Loyalty Card usage in Milk Dataset). Some suggestions or ideas are to: 

1.	Estimate Quantity Demanded as a function of price (and similar prices) using a Log Transformation. You can also include marketing strategies in your regression.
2.	Combine Gross Margin information to advise the firm on maximizing profits. To avoid sales cannibalization, simultaneously include multiple products. Depending on how you set this up, you might be able to use Solver in Excel to fin the optimal strategy. It is a NLP.
3.	The estimates of margins and demand are only estimates. Perform Monte Carlo analysis to simulate different strategies even if your estimate is not perfect (draw the regression coefficients from a normal with mean = estimate and standard deviation = standard error). Report on the results from these simulations.

# Set-up

In [1]:
# import packages 
import pandas as pd #pandas 
import numpy  as np #numpy 
from numpy import arange # for ranges with floats
import statsmodels.formula.api as smf # predictive modeling with nice outputs
import matplotlib.pyplot as plt
import seaborn as sns

# set options 
pd.set_option("display.max_rows", 999)
pd.set_option("display.max_columns", 50)
np.random.seed(42)  

# importing file 
df = pd.read_excel('OJ_Data.xlsx')

In [2]:
# Helper functions 

# Make binary function 
def make_binary(df):
    
    for col in df.columns:
        
        if 'feat' in col \
        or 'disp' in col:
            
            for index, value in df.iterrows():
                
                if df.loc[index, col] >= 0.5:
                    df.loc[index, col] = 1
                else:
                    df.loc[index, col] = 0
        
            df[col] = df[col].astype(int)


# Shuffle dataframe function
def shuffle(df, n = 1, axis = 0):     
    df = df.copy()
    for _ in range(n):
        df.apply(np.random.shuffle, axis = axis)
        return df

# Source:
# https://stackoverflow.com/questions/15772009/shuffling-permutating-a-dataframe-in-pandas

In [3]:
# Data cleaning 

# Clean binary variables
make_binary(df)


# Log transformations 

# price
df['log_price1'] = np.log(df['price1'])
df['log_price2'] = np.log(df['price2'])
df['log_price3'] = np.log(df['price3'])
df['log_price4'] = np.log(df['price4'])
df['log_price5'] = np.log(df['price5'])

# sales
df['log_sales1'] = np.log(df['sales1'])
df['log_sales2'] = np.log(df['sales2'])
df['log_sales3'] = np.log(df['sales3'])
df['log_sales4'] = np.log(df['sales4'])
df['log_sales5'] = np.log(df['sales5'])

# Part 1: Regression

## Product 1: Tropicana Premium 64 oz

In [4]:
# step 1: build a model
lm_best = smf.ols(formula =  """log_sales1 ~ log_price1 +
                                        log_price2 +
                                        log_price3 +
                                        log_price4 +
                                        log_price5 +
                                        disp1 +
                                        feat1""",
                                        data = df)


# step 2: fit the model based on the data
results_1 = lm_best.fit()

# step 3: analyze the summary output
print(results_1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             log_sales1   R-squared:                       0.794
Model:                            OLS   Adj. R-squared:                  0.781
Method:                 Least Squares   F-statistic:                     59.46
Date:                Mon, 29 Mar 2021   Prob (F-statistic):           3.56e-34
Time:                        15:34:11   Log-Likelihood:                -39.592
No. Observations:                 116   AIC:                             95.18
Df Residuals:                     108   BIC:                             117.2
Df Model:                           7
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      3.3030      1.109      2.977      0.004       1.104       5.502
log_price1    -2.6540      0.232    -11.432      0.000      -3.114      -2.194
log_price2     0.1441      0.317      0.455      0.650      -0.483       0.772
log_price3     0.5562      0.185      3.008      0.003       0.190       0.923
log_price4    -0.0630      0.202     -0.311      0.756      -0.464       0.338
log_price5     0.0250      0.157      0.160      0.874      -0.286       0.336
disp1         -0.0262      0.091     -0.289      0.773      -0.206       0.154
feat1          0.6440      0.097      6.640      0.000       0.452       0.836
==============================================================================
Omnibus:                        5.601   Durbin-Watson:                   1.733
Prob(Omnibus):                  0.061   Jarque-Bera (JB):                8.622
Skew:                           0.010   Prob(JB):                       0.0134
Kurtosis:                       4.335   Cond. No.                         256.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [5]:
# Re-running the the regression without variables with p-values above 0.05

# step 1: build a model
lm_best = smf.ols(formula =  """log_sales1 ~ log_price1 +
                                        log_price3 +
                                        disp1 +
                                        feat1""",
                                        data = df)


# step 2: fit the model based on the data
results_1_opt = lm_best.fit()

# step 3: analyze the summary output
print(results_1_opt.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             log_sales1   R-squared:                       0.793
Model:                            OLS   Adj. R-squared:                  0.786
Method:                 Least Squares   F-statistic:                     106.5
Date:                Mon, 29 Mar 2021   Prob (F-statistic):           4.46e-37
Time:                        15:34:12   Log-Likelihood:                -39.767
No. Observations:                 116   AIC:                             89.53
Df Residuals:                     111   BIC:                             103.3
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      3.0708      0.817      3.759      0.000       1.452       4.690
log_price1    -2.6331      0.213    -12.379      0.000      -3.055      -2.212
log_price3     0.5614      0.179      3.140      0.002       0.207       0.916
disp1         -0.0199      0.088     -0.227      0.821      -0.193       0.154
feat1          0.6419      0.095      6.759      0.000       0.454       0.830
==============================================================================
Omnibus:                        5.505   Durbin-Watson:                   1.715
Prob(Omnibus):                  0.064   Jarque-Bera (JB):                8.276
Skew:                          -0.053   Prob(JB):                       0.0160
Kurtosis:                       4.304   Cond. No.                         122.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

## Product 2: Tropicana Premium 96 oz

In [6]:
# step 1: build a model
lm_best = smf.ols(formula =  """log_sales2 ~ log_price1 +
                                        log_price2 +
                                        log_price3 +
                                        log_price4 +
                                        log_price5 +
                                        disp2 +
                                        feat2""",
                                        data = df)


# step 2: fit the model based on the data
results_2 = lm_best.fit()

# step 3: analyze the summary output
print(results_2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             log_sales2   R-squared:                       0.558
Model:                            OLS   Adj. R-squared:                  0.530
Method:                 Least Squares   F-statistic:                     19.51
Date:                Mon, 29 Mar 2021   Prob (F-statistic):           1.15e-16
Time:                        15:34:12   Log-Likelihood:                 11.315
No. Observations:                 116   AIC:                            -6.631
Df Residuals:                     108   BIC:                             15.40
Df Model:                           7
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      5.2759      0.730      7.225      0.000       3.829       6.723
log_price1     0.3283      0.112      2.933      0.004       0.106       0.550
log_price2    -1.5455      0.242     -6.395      0.000      -2.025      -1.066
log_price3     0.0490      0.119      0.411      0.682      -0.187       0.286
log_price4    -0.0348      0.133     -0.262      0.794      -0.299       0.229
log_price5    -0.1156      0.101     -1.143      0.256      -0.316       0.085
disp2          0.0374      0.058      0.644      0.521      -0.078       0.152
feat2          0.2985      0.072      4.159      0.000       0.156       0.441
==============================================================================
Omnibus:                        0.793   Durbin-Watson:                   1.237
Prob(Omnibus):                  0.673   Jarque-Bera (JB):                0.375
Skew:                           0.008   Prob(JB):                        0.829
Kurtosis:                       3.278   Cond. No.                         263.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [7]:
# Re-running the the regression without variables with p-values above 0.05

# step 1: build a model
lm_best = smf.ols(formula =  """log_sales2 ~ log_price1 +
                                        log_price2 +
                                        disp2 +
                                        feat2""",
                                        data = df)


# step 2: fit the model based on the data
results_2_opt = lm_best.fit()

# step 3: analyze the summary output
print(results_2_opt.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             log_sales2   R-squared:                       0.552
Model:                            OLS   Adj. R-squared:                  0.536
Method:                 Least Squares   F-statistic:                     34.20
Date:                Mon, 29 Mar 2021   Prob (F-statistic):           1.39e-18
Time:                        15:34:12   Log-Likelihood:                 10.491
No. Observations:                 116   AIC:                            -10.98
Df Residuals:                     111   BIC:                             2.786
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      5.4557      0.631      8.643      0.000       4.205       6.706
log_price1     0.3164      0.110      2.884      0.005       0.099       0.534
log_price2    -1.5982      0.225     -7.106      0.000      -2.044      -1.153
disp2          0.0305      0.057      0.539      0.591      -0.082       0.143
feat2          0.3048      0.070      4.331      0.000       0.165       0.444
==============================================================================
Omnibus:                        1.401   Durbin-Watson:                   1.260
Prob(Omnibus):                  0.496   Jarque-Bera (JB):                0.916
Skew:                           0.106   Prob(JB):                        0.633
Kurtosis:                       3.380   Cond. No.                         140.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

## Product 3: Topicana 64 oz

In [8]:
# step 1: build a model
lm_best = smf.ols(formula =  """log_sales3 ~ log_price1 +
                                        log_price2 +
                                        log_price3 +
                                        log_price4 +
                                        log_price5 +
                                        disp3 +
                                        feat3""",
                                        data = df)


# step 2: fit the model based on the data
results_3 = lm_best.fit()

# step 3: analyze the summary output
print(results_3.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             log_sales3   R-squared:                       0.712
Model:                            OLS   Adj. R-squared:                  0.694
Method:                 Least Squares   F-statistic:                     38.20
Date:                Mon, 29 Mar 2021   Prob (F-statistic):           1.85e-26
Time:                        15:34:12   Log-Likelihood:                -126.90
No. Observations:                 116   AIC:                             269.8
Df Residuals:                     108   BIC:                             291.8
Df Model:                           7
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      5.3681      2.481      2.164      0.033       0.450      10.286
log_price1     1.1542      0.364      3.168      0.002       0.432       1.876
log_price2     1.0704      0.662      1.618      0.109      -0.241       2.382
log_price3    -4.4184      0.474     -9.324      0.000      -5.358      -3.479
log_price4     1.4386      0.457      3.151      0.002       0.534       2.344
log_price5     0.0745      0.333      0.224      0.824      -0.586       0.735
disp3          0.2024      0.171      1.186      0.238      -0.136       0.541
feat3          0.9833      0.170      5.787      0.000       0.646       1.320
==============================================================================
Omnibus:                       11.283   Durbin-Watson:                   1.641
Prob(Omnibus):                  0.004   Jarque-Bera (JB):               13.336
Skew:                           0.578   Prob(JB):                      0.00127
Kurtosis:                       4.192   Cond. No.                         270.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [9]:
# Re-running the the regression without variables with p-values above 0.05

# step 1: build a model
lm_best = smf.ols(formula =  """log_sales3 ~ log_price1 +
                                        log_price3 +
                                        log_price4 +
                                        disp3 +
                                        feat3""",
                                        data = df)


# step 2: fit the model based on the data
results_3_opt = lm_best.fit()

# step 3: analyze the summary output
print(results_3_opt.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             log_sales3   R-squared:                       0.705
Model:                            OLS   Adj. R-squared:                  0.691
Method:                 Least Squares   F-statistic:                     52.46
Date:                Mon, 29 Mar 2021   Prob (F-statistic):           1.43e-27
Time:                        15:34:12   Log-Likelihood:                -128.44
No. Observations:                 116   AIC:                             268.9
Df Residuals:                     110   BIC:                             285.4
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      3.0170      2.029      1.487      0.140      -1.004       7.038
log_price1     1.3084      0.354      3.694      0.000       0.606       2.010
log_price3    -4.3149      0.471     -9.155      0.000      -5.249      -3.381
log_price4     1.5322      0.455      3.367      0.001       0.630       2.434
disp3          0.1899      0.171      1.110      0.269      -0.149       0.529
feat3          1.0187      0.169      6.036      0.000       0.684       1.353
==============================================================================
Omnibus:                        8.785   Durbin-Watson:                   1.581
Prob(Omnibus):                  0.012   Jarque-Bera (JB):                9.531
Skew:                           0.499   Prob(JB):                      0.00852
Kurtosis:                       3.988   Cond. No.                         171.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

## Product 4: Minute Maid 64 oz

In [10]:
# step 1: build a model
lm_best = smf.ols(formula =  """log_sales4 ~ log_price1 +
                                        log_price2 +
                                        log_price3 +
                                        log_price4 +
                                        log_price5 +
                                        disp4 +
                                        feat4""",
                                        data = df)


# step 2: fit the model based on the data
results_4 = lm_best.fit()

# step 3: analyze the summary output
print(results_4.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             log_sales4   R-squared:                       0.752
Model:                            OLS   Adj. R-squared:                  0.736
Method:                 Least Squares   F-statistic:                     46.70
Date:                Mon, 29 Mar 2021   Prob (F-statistic):           7.43e-30
Time:                        15:34:12   Log-Likelihood:                -74.636
No. Observations:                 116   AIC:                             165.3
Df Residuals:                     108   BIC:                             187.3
Df Model:                           7
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      6.3356      1.633      3.879      0.000       3.098       9.573
log_price1     0.5407      0.243      2.228      0.028       0.060       1.022
log_price2     0.2397      0.423      0.567      0.572      -0.598       1.078
log_price3     0.6079      0.261      2.328      0.022       0.090       1.125
log_price4    -2.7045      0.390     -6.935      0.000      -3.478      -1.931
log_price5     0.5532      0.212      2.613      0.010       0.134       0.973
disp4          0.1909      0.132      1.442      0.152      -0.071       0.453
feat4          0.8679      0.131      6.646      0.000       0.609       1.127
==============================================================================
Omnibus:                       31.249   Durbin-Watson:                   1.827
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               68.303
Skew:                           1.064   Prob(JB):                     1.47e-15
Kurtosis:                       6.099   Cond. No.                         279.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [11]:
# Re-running the the regression without variables with p-values above 0.05

# step 1: build a model
lm_best = smf.ols(formula =  """log_sales4 ~ log_price1 +
                                        log_price3 +
                                        log_price4 +
                                        log_price5 +
                                        disp4 +
                                        feat4""",
                                        data = df)


# step 2: fit the model based on the data
results_4_opt = lm_best.fit()

# step 3: analyze the summary output
print(results_4_opt.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             log_sales4   R-squared:                       0.751
Model:                            OLS   Adj. R-squared:                  0.737
Method:                 Least Squares   F-statistic:                     54.78
Date:                Mon, 29 Mar 2021   Prob (F-statistic):           1.12e-30
Time:                        15:34:12   Log-Likelihood:                -74.809
No. Observations:                 116   AIC:                             163.6
Df Residuals:                     109   BIC:                             182.9
Df Model:                           6
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      5.9598      1.488      4.005      0.000       3.011       8.909
log_price1     0.5653      0.238      2.376      0.019       0.094       1.037
log_price3     0.6214      0.259      2.397      0.018       0.108       1.135
log_price4    -2.6623      0.382     -6.976      0.000      -3.419      -1.906
log_price5     0.5762      0.207      2.783      0.006       0.166       0.987
disp4          0.1964      0.132      1.492      0.138      -0.064       0.457
feat4          0.8731      0.130      6.724      0.000       0.616       1.131
==============================================================================
Omnibus:                       29.629   Durbin-Watson:                   1.828
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               63.769
Skew:                           1.013   Prob(JB):                     1.42e-14
Kurtosis:                       6.015   Cond. No.                         234.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

## Product 5: Dominick's 64 oz

In [12]:
# step 1: build a model
lm_best = smf.ols(formula =  """log_sales5 ~ log_price1 +
                                        log_price2 +
                                        log_price3 +
                                        log_price4 +
                                        log_price5 +
                                        disp5 +
                                        feat5""",
                                        data = df)


# step 2: fit the model based on the data
results_5 = lm_best.fit()

# step 3: analyze the summary output
print(results_5.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             log_sales5   R-squared:                       0.667
Model:                            OLS   Adj. R-squared:                  0.646
Method:                 Least Squares   F-statistic:                     30.94
Date:                Mon, 29 Mar 2021   Prob (F-statistic):           4.05e-23
Time:                        15:34:12   Log-Likelihood:                -118.15
No. Observations:                 116   AIC:                             252.3
Df Residuals:                     108   BIC:                             274.3
Df Model:                           7
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -0.5951      2.166     -0.275      0.784      -4.888       3.698
log_price1     0.0985      0.336      0.293      0.770      -0.567       0.764
log_price2    -1.6637      0.611     -2.722      0.008      -2.875      -0.452
log_price3     1.0508      0.365      2.876      0.005       0.327       1.775
log_price4     1.1025      0.397      2.778      0.006       0.316       1.889
log_price5    -3.2416      0.352     -9.219      0.000      -3.939      -2.545
disp5          0.2818      0.144      1.958      0.053      -0.004       0.567
feat5          0.6590      0.155      4.256      0.000       0.352       0.966
==============================================================================
Omnibus:                        4.625   Durbin-Watson:                   1.679
Prob(Omnibus):                  0.099   Jarque-Bera (JB):                4.684
Skew:                          -0.270   Prob(JB):                       0.0962
Kurtosis:                       3.823   Cond. No.                         254.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [13]:
# Re-running the the regression without variables with p-values above 0.05

# step 1: build a model
lm_best_opt = smf.ols(formula =  """log_sales5 ~ log_price2 +
                                        log_price3 +
                                        log_price4 +
                                        log_price5 +
                                        disp5 +
                                        feat5""",
                                        data = df)


# step 2: fit the model based on the data
results_5_opt = lm_best_opt.fit()

# step 3: analyze the summary output
print(results_5_opt.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             log_sales5   R-squared:                       0.667
Model:                            OLS   Adj. R-squared:                  0.649
Method:                 Least Squares   F-statistic:                     36.39
Date:                Mon, 29 Mar 2021   Prob (F-statistic):           6.66e-24
Time:                        15:34:12   Log-Likelihood:                -118.19
No. Observations:                 116   AIC:                             250.4
Df Residuals:                     109   BIC:                             269.7
Df Model:                           6
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -0.6726      2.141     -0.314      0.754      -4.915       3.570
log_price2    -1.6261      0.595     -2.733      0.007      -2.806      -0.447
log_price3     1.0544      0.364      2.900      0.005       0.334       1.775
log_price4     1.1239      0.389      2.893      0.005       0.354       1.894
log_price5    -3.2319      0.349     -9.272      0.000      -3.923      -2.541
disp5          0.2854      0.143      1.999      0.048       0.002       0.568
feat5          0.6610      0.154      4.291      0.000       0.356       0.966
==============================================================================
Omnibus:                        4.516   Durbin-Watson:                   1.680
Prob(Omnibus):                  0.105   Jarque-Bera (JB):                4.471
Skew:                          -0.274   Prob(JB):                        0.107
Kurtosis:                       3.790   Cond. No.                         230.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

<br><br>

# Part 2: Monte Carlo

## Constant Variables

In [14]:
# Setup constant variables

# Ounces per SKU
oz_1 = 64
oz_2 = 96
oz_3 = 64
oz_4 = 64
oz_5 = 64

# Assume gross margin is averaged per SKU
grmar1_avg = df['grmar1'].mean()
grmar2_avg = df['grmar2'].mean()
grmar3_avg = df['grmar3'].mean()
grmar4_avg = df['grmar4'].mean()
grmar5_avg = df['grmar5'].mean()


##############################################################################
# Set up random draw parameters for coefficients - SKU1

# intercept 
intercept_mu_1    = results_1_opt.params[0]  # coefficient from regression
intercept_sigma_1 = results_1_opt.bse[0]     # standard error from regression

# price SKU1
B1_mu_P1_1    = results_1_opt.params[1]      # coefficient from regression
B1_sigma_P1_1 = results_1_opt.bse[1]         # standard error from regression

# price SKU3
B2_mu_P3_1    = results_1_opt.params[2]      # coefficient from regression
B2_sigma_P3_1 = results_1_opt.bse[2]         # standard error from regression

# disp1 SKU1
B3_mu_D1_1 = results_1_opt.params[3]         # coefficient from regression

# feat1 SKU1
B4_mu_F1_1 = results_1_opt.params[4]         # coefficient from regression


##############################################################################
# Set up random draw parameters for coefficients - SKU2

# intercept 
intercept_mu_2    = results_2_opt.params[0] # coefficient from regression
intercept_sigma_2 = results_2_opt.bse[0]    # standard error from regression

# price SKU1
B1_mu_P1_2    = results_2_opt.params[1]     # coefficient from regression
B1_sigma_P1_2 = results_2_opt.bse[1]        # standard error from regression

# price SKU2
B2_mu_P2_2    = results_2_opt.params[2]     # coefficient from regression
B2_sigma_P2_2 = results_2_opt.bse[2]        # standard error from regression

# disp2 SKU2
B3_mu_D2_2 = results_2_opt.params[3]        # coefficient from regression

# feat2 SKU2
B4_mu_F2_2 = results_2_opt.params[4]        # coefficient from regression


##############################################################################
# Set up random draw parameters for coefficients - SKU3

# intercept 
intercept_mu_3    = results_3_opt.params[0]  # coefficient from regression
intercept_sigma_3 = results_3_opt.bse[0]     # standard error from regression

# price SKU1
B1_mu_P1_3    = results_3_opt.params[1]      # coefficient from regression
B1_sigma_P1_3 = results_3_opt.bse[1]         # standard error from regression

# price SKU3 
B2_mu_P3_3    = results_3_opt.params[2]      # coefficient from regression
B2_sigma_P3_3 = results_3_opt.bse[2]         # standard error from regression

# feat2 SKU4
B3_mu_P4_3    = results_3_opt.params[3]      # coefficient from regression
B3_sigma_P4_3 = results_3_opt.bse[3]         # standard error from regression

# disp3 SKU3
B4_mu_D3_3 = results_3_opt.params[4]         # coefficient from regression

# feat3 SKU3
B5_mu_F3_3 = results_3_opt.params[5]         # coefficient from regression


##############################################################################
# Set up random draw parameters for coefficients - SKU4

# intercept 
intercept_mu_4    = results_4_opt.params[0]  # coefficient from regression
intercept_sigma_4 = results_4_opt.bse[0]     # standard error from regression

# price SKU1
B1_mu_P1_4    = results_4_opt.params[1]      # coefficient from regression
B1_sigma_P1_4 = results_4_opt.bse[1]         # standard error from regression

# price SKU3
B2_mu_P3_4    = results_4_opt.params[2]      # coefficient from regression
B2_sigma_P3_4 = results_4_opt.bse[2]         # standard error from regression

# price  SKU4
B3_mu_P4_4    = results_4_opt.params[3]      # coefficient from regression
B3_sigma_P4_4 = results_4_opt.bse[3]         # standard error from regression

# price SKU5
B4_mu_P5_4    = results_4_opt.params[4]      # coefficient from regression
B4_sigma_P5_4 = results_4_opt.bse[4]         # standard error from regression

# disp4 SKU4
B5_mu_D4_4 = results_4_opt.params[5]         # coefficient from regression

# feat4 SKU4
B6_mu_F4_4 = results_4_opt.params[6]         # coefficient from regression


##############################################################################
# Set up random draw parameters for coefficients - SKU5 

# intercept 
intercept_mu_5    = results_5_opt.params[0]  # coefficient from regression
intercept_sigma_5 = results_5_opt.bse[0]     # standard error from regression

# price SKU2
B1_mu_P2_5    = results_5_opt.params[1]      # coefficient from regression
B1_sigma_P2_5 = results_5_opt.bse[1]         # standard error from regression

# price SKU3
B2_mu_P3_5    = results_5_opt.params[2]      # coefficient from regression
B2_sigma_P3_5 = results_5_opt.bse[2]         # standard error from regression

# price SKU4
B3_mu_P4_5    = results_5_opt.params[3]      # coefficient from regression
B3_sigma_P4_5 = results_5.bse[3]             # standard error from regression

# price SKU5
B4_mu_P5_5    = results_5_opt.params[4]      # coefficient from regression
B4_sigma_P5_5 = results_5_opt.bse[4]         # standard error from regression

# disp SKU5
B5_mu_D5_5    = results_5_opt.params[5]      # coefficient from regression

# feat5 SKU5
B6_mu_F5_5    = results_5_opt.params[6]      # coefficient from regression

## Price Simulations

In [15]:
# Price Simulations

# Number of combinations of prices across SKUs'
n = 5

# Min Max Prices for SKU#
min_price1 = df['price1'].min()
max_price1 = df['price1'].max()
min_price2 = df['price2'].min()
max_price2 = df['price2'].max()
min_price3 = df['price3'].min()
max_price3 = df['price3'].max()
min_price4 = df['price4'].min()
max_price4 = df['price4'].max()
min_price5 = df['price5'].min()
max_price5 = df['price5'].max()

price_increment_1 = (max_price1 - min_price1)/n
price_increment_2 = (max_price2 - min_price2)/n
price_increment_3 = (max_price3 - min_price3)/n
price_increment_4 = (max_price4 - min_price4)/n
price_increment_5 = (max_price5 - min_price5)/n

price_df = pd.DataFrame()

price_df['P_1'] = arange(min_price1, max_price1, price_increment_1)
price_df['P_2'] = arange(min_price2, max_price2, price_increment_2)
price_df['P_3'] = arange(min_price3, max_price3, price_increment_3)
price_df['P_4'] = arange(min_price4, max_price4, price_increment_4)
price_df['P_5'] = arange(min_price5, max_price5, price_increment_5)

price_df = shuffle(df = price_df)
price_df

        P_1       P_2       P_3       P_4       P_5
0  0.032563  0.051021  0.027656  0.020156  0.015469
1  0.051031  0.041729  0.023281  0.025469  0.024844
2  0.038719  0.046375  0.036406  0.030781  0.029531
3  0.026406  0.037083  0.040781  0.036094  0.020156
4  0.044875  0.055667  0.032031  0.041406  0.034219

## Profit Simulations

In [19]:
# Monte Carlo Simulation

# Number of simulations per combinations of prices across SKUs'
number_sims = 10_000

# Store results from each simulation here
final_stats = []

# Loop over price dataframe
for i in range(len(price_df)):
    
    # Extract price per SKU as log
    P_1 = np.log(price_df.iloc[i, 0])
    P_2 = np.log(price_df.iloc[i, 1])
    P_3 = np.log(price_df.iloc[i, 2])
    P_4 = np.log(price_df.iloc[i, 3])
    P_5 = np.log(price_df.iloc[i, 4])
    
    # Placeholder
    all_stats = []

    # Begin Simulation Loop
    for i in range(number_sims):
        
        ###########
        #  SKU1   # 
        ###########
        
        intercept_1 = np.random.normal(intercept_mu_1, intercept_sigma_1)
        B1_1   = np.random.normal(B1_mu_P1_1, B1_sigma_P1_1)
        B2_1   = np.random.normal(B2_mu_P3_1, B2_sigma_P3_1)   
        feat1  = np.random.randint(2)
        disp1  = np.random.randint(2)
        
        sales_1 = np.exp(intercept_1 \
                + B1_1 * P_1 \
                + B2_1 * P_3 \
                + B3_mu_D1_1 * disp1 \
                + B4_mu_F1_1 * feat1)
        revenue_1 = sales_1 * oz_1 * np.exp(P_1)
        profits_1 = revenue_1 * grmar1_avg
        
        
        ###########
        #  SKU2   # 
        ###########
        
        intercept_2 = np.random.normal(intercept_mu_2, intercept_sigma_2)
        B1_2   = np.random.normal(B1_mu_P1_2, B1_sigma_P1_2)
        B2_2   = np.random.normal(B2_mu_P2_2, B2_sigma_P2_2)   
        feat2  = np.random.randint(2)
        disp2  = np.random.randint(2)
        
        sales_2 = np.exp(intercept_2 \
                + B1_2 * P_1 \
                + B2_2 * P_2 \
                + B3_mu_D2_2 * disp2 \
                + B4_mu_F2_2 * feat2)
        
        revenue_2 = sales_2 * oz_2 * np.exp(P_2)
        profits_2 = revenue_2 * grmar2_avg
        
                
        ###########
        #  SKU3   # 
        ###########
        
        intercept_3 = np.random.normal(intercept_mu_3, intercept_sigma_3)
        B1_3   = np.random.normal(B1_mu_P1_3, B1_sigma_P1_3)
        B2_3   = np.random.normal(B2_mu_P3_3, B2_sigma_P3_3)   
        B3_3   = np.random.normal(B3_mu_P4_3, B3_sigma_P4_3) 
        feat3  = np.random.randint(2)
        disp3  = np.random.randint(2)
        
        sales_3 = np.exp(intercept_3 \
                + B1_3 * P_1 \
                + B2_3 * P_3 \
                + B3_3 * P_4 \
                + B4_mu_D3_3 * disp3 \
                + B5_mu_F3_3 * feat3)
        
        revenue_3 = sales_3 * oz_3 * np.exp(P_3)
        profits_3 = revenue_3 * grmar3_avg
        
        
        ###########
        #  SKU4   # 
        ###########
        
        intercept_4 = np.random.normal(intercept_mu_4, intercept_sigma_4)
        B1_4   = np.random.normal(B1_mu_P1_4, B1_sigma_P1_4)
        B2_4   = np.random.normal(B2_mu_P3_4, B2_sigma_P3_4)   
        B3_4   = np.random.normal(B3_mu_P4_4, B3_sigma_P4_5) 
        B4_4   = np.random.normal(B4_mu_P5_5, B4_sigma_P5_5)
        feat4  = np.random.randint(2)
        disp4  = np.random.randint(2)
        
        sales_4 = np.exp(intercept_4 \
                + B1_4 * P_1 \
                + B2_4 * P_3 \
                + B3_4 * P_4 \
                + B4_4 * P_5 \
                + B5_mu_D4_4 * disp4 \
                + B6_mu_F4_4 * feat4)
        
        revenue_4 = sales_4 * oz_4 * np.exp(P_4)
        profits_4 = revenue_4 * grmar4_avg
        
        
        ###########
        #  SKU5   # 
        ###########
        
        intercept_5 = np.random.normal(intercept_mu_5, intercept_sigma_5)
        B1_5   = np.random.normal(B1_mu_P2_5, B1_sigma_P2_5)
        B2_5   = np.random.normal(B2_mu_P3_5, B2_sigma_P3_5)   
        B3_5   = np.random.normal(B3_mu_P4_5, B3_sigma_P4_5) 
        B4_5   = np.random.normal(B4_mu_P5_5, B4_sigma_P5_5) 
        feat5  = np.random.randint(2)
        disp5  = np.random.randint(2)
        
        sales_5 = np.exp(intercept_5 \
                + B1_5 * P_2 \
                + B2_5 * P_3 \
                + B3_5 * P_4 \
                + B4_5 * P_5 \
                + B5_mu_D5_5 * disp5 \
                + B6_mu_F5_5 * feat5)
        
        revenue_5 = sales_5 * oz_5 * np.exp(P_5)
        profits_5 = revenue_5 * grmar5_avg
        
        
        ####################
        #  Appending SKUs  # 
        ####################
        
        
        all_stats.append([sales_5, revenue_5, profits_5, disp5, feat5, 
                          sales_4, revenue_4, profits_4, disp4, feat4, 
                          sales_3, revenue_3, profits_3, disp3, feat3,
                          sales_2, revenue_2, profits_2, disp2, feat2,
                          sales_1, revenue_1, profits_1, disp1, feat1,])
        
           
    results_df = pd.DataFrame.from_records(all_stats, columns =
    ['units_sold_5','revenue_5','profits_5','disp_5','feat_5',
     'units_sold_4','revenue_4','profits_4','disp_4','feat_4',
     'units_sold_3','revenue_3','profits_3','disp_3','feat_3',
     'units_sold_2','revenue_2','profits_2','disp_2','feat_2',
     'units_sold_1','revenue_1','profits_1','disp_1','feat_1'])
        
    final_stats.append([np.exp(P_5), np.exp(P_4), np.exp(P_3),
                        np.exp(P_2), np.exp(P_1),
                        results_df['profits_5'].mean(),
                        results_df['profits_4'].mean(),
                        results_df['profits_3'].mean(),
                        results_df['profits_2'].mean(),
                        results_df['profits_1'].mean(),
                        results_df['feat_5'].value_counts().idxmax(), # most frequent value
                        results_df['feat_4'].value_counts().idxmax(),
                        results_df['feat_3'].value_counts().idxmax(),
                        results_df['feat_2'].value_counts().idxmax(),
                        results_df['feat_1'].value_counts().idxmax(),
                        results_df['disp_5'].value_counts().idxmax(),
                        results_df['disp_4'].value_counts().idxmax(),
                        results_df['disp_3'].value_counts().idxmax(),
                        results_df['disp_2'].value_counts().idxmax(),
                        results_df['disp_1'].value_counts().idxmax()])
    
final_stats_df = pd.DataFrame.from_records(final_stats, columns =
                ['Price per Oz_5', 'Price per Oz_4',
                 'Price per Oz_3', 'Price per Oz_2', 'Price per Oz_1',
                 'Profits_5', 'Profits_4', 
                 'Profits_3', 'Profits_2', 'Profits_1',
                 'Feat_5', 'Feat_4', 'Feat_3', 'Feat_2', 'Feat_1',
                 'Disp_5', 'Disp_4', 'Disp_3', 'Disp_2', 'Disp_1'])

final_stats_df['Total Profits'] = final_stats_df['Profits_5']\
                                + final_stats_df['Profits_4']\
                                + final_stats_df['Profits_3']\
                                + final_stats_df['Profits_2']\
                                + final_stats_df['Profits_1']


final_stats_df

,Price per Oz_5,Price per Oz_4,Price per Oz_3,Price per Oz_2,Price per Oz_1,Profits_5,Profits_4,Profits_3,Profits_2,Profits_1,Feat_5,Feat_4,Feat_3,Feat_2,Feat_1,Disp_5,Disp_4,Disp_3,Disp_2,Disp_1,Total Profits
0,0.015469,0.020156,0.027656,0.051021,0.032562,4.519416e+06,4.797824e+12,6.654615e+05,25033.530072,45807.388966,0,0,0,0,1,1,1,0,0,1,4.797829e+12
1,0.024844,0.025469,0.023281,0.041729,0.051031,1.273850e+06,4.369079e+11,1.217854e+07,33405.757564,19060.387887,0,1,1,1,0,0,1,0,0,0,4.369214e+11
2,0.029531,0.030781,0.036406,0.046375,0.038719,1.894165e+06,2.563721e+11,6.742613e+05,28174.348837,37561.808372,1,1,0,1,1,0,0,1,1,0,2.563747e+11
3,0.020156,0.036094,0.040781,0.037083,0.026406,9.020135e+06,6.656313e+11,3.397620e+05,30445.356728,77975.048483,1,1,0,0,1,0,0,0,0,0,6.656408e+11
4,0.034219,0.041406,0.032031,0.055667,0.044875,4.586352e+05,5.762704e+10,1.191572e+06,25718.017901,27035.227677,0,1,1,1,1,1,0,0,0,1,5.762874e+10

In [20]:
# Identify Best Pricing & Marketing Settings for Maximum Profit for SKU5
index = final_stats_df.loc[final_stats_df['Total Profits'] == final_stats_df['Total Profits'].max(),:].index
final_stats_df.iloc[index,:]

,Price per Oz_5,Price per Oz_4,Price per Oz_3,Price per Oz_2,Price per Oz_1,Profits_5,Profits_4,Profits_3,Profits_2,Profits_1,Feat_5,Feat_4,Feat_3,Feat_2,Feat_1,Disp_5,Disp_4,Disp_3,Disp_2,Disp_1,Total Profits
0,0.015469,0.020156,0.027656,0.051021,0.032562,4.519416e+06,4.797824e+12,665461.461829,25033.530072,45807.388966,0,0,0,0,1,1,1,0,0,1,4.797829e+12

In [21]:
# Monte Carlo Simulation

# Number of simulations per combinations of prices across SKUs'
number_sims = 10_000

# Store results from each simulation here
final_stats = []

# Loop over price dataframe
for i in range(len(price_df)):
    
    # Extract price per SKU as log
    P_1 = np.log(price_df.iloc[i, 0])
    P_2 = np.log(price_df.iloc[i, 1])
    P_3 = np.log(price_df.iloc[i, 2])
    P_4 = np.log(price_df.iloc[i, 3])
    P_5 = np.log(price_df.iloc[i, 4])
    
    # Placeholder
    all_stats = []

    # Begin Simulation Loop
    for i in range(number_sims):
        
        ###########
        #  SKU1   # 
        ###########
        
        intercept_1 = np.random.normal(intercept_mu_1, intercept_sigma_1)
        B1_1   = np.random.normal(B1_mu_P1_1, B1_sigma_P1_1)
        B2_1   = np.random.normal(B2_mu_P3_1, B2_sigma_P3_1)   
        feat1  = np.random.randint(2)
        disp1  = np.random.randint(2)
        
        sales_1 = intercept_1 \
                + np.exp(B1_1 * P_1 \
                + B2_1 * P_3) \
                + B3_mu_D1_1 * disp1 \
                + B4_mu_F1_1 * feat1
        revenue_1 = sales_1 * oz_1 * np.exp(P_1)
        profits_1 = revenue_1 * grmar1_avg
        
        
        ###########
        #  SKU2   # 
        ###########
        
        intercept_2 = np.random.normal(intercept_mu_2, intercept_sigma_2)
        B1_2   = np.random.normal(B1_mu_P1_2, B1_sigma_P1_2)
        B2_2   = np.random.normal(B2_mu_P2_2, B2_sigma_P2_2)   
        feat2  = np.random.randint(2)
        disp2  = np.random.randint(2)
        
        sales_2 = intercept_2 \
                + np.exp(B1_2 * P_1 \
                + B2_2 * P_2) \
                + B3_mu_D2_2 * disp2 \
                + B4_mu_F2_2 * feat2
        
        revenue_2 = sales_2 * oz_2 * np.exp(P_2)
        profits_2 = revenue_2 * grmar2_avg
        
                
        ###########
        #  SKU3   # 
        ###########
        
        intercept_3 = np.random.normal(intercept_mu_3, intercept_sigma_3)
        B1_3   = np.random.normal(B1_mu_P1_3, B1_sigma_P1_3)
        B2_3   = np.random.normal(B2_mu_P3_3, B2_sigma_P3_3)   
        B3_3   = np.random.normal(B3_mu_P4_3, B3_sigma_P4_3) 
        feat3  = np.random.randint(2)
        disp3  = np.random.randint(2)
        
        sales_3 = intercept_3 \
                + np.exp(B1_3 * P_1 \
                + B2_3 * P_3 \
                + B3_3 * P_4) \
                + B4_mu_D3_3 * disp3 \
                + B5_mu_F3_3 * feat3
        
        revenue_3 = sales_3 * oz_3 * np.exp(P_3)
        profits_3 = revenue_3 * grmar3_avg
        
        
        ###########
        #  SKU4   # 
        ###########
        
        intercept_4 = np.random.normal(intercept_mu_4, intercept_sigma_4)
        B1_4   = np.random.normal(B1_mu_P1_4, B1_sigma_P1_4)
        B2_4   = np.random.normal(B2_mu_P3_4, B2_sigma_P3_4)   
        B3_4   = np.random.normal(B3_mu_P4_4, B3_sigma_P4_5) 
        B4_4   = np.random.normal(B4_mu_P5_5, B4_sigma_P5_5)
        feat4  = np.random.randint(2)
        disp4  = np.random.randint(2)
        
        sales_4 = intercept_4 \
                + np.exp(B1_4 * P_1 \
                + B2_4 * P_3 \
                + B3_4 * P_4 \
                + B4_4 * P_5) \
                + B5_mu_D4_4 * disp4 \
                + B6_mu_F4_4 * feat4
        
        revenue_4 = sales_4 * oz_4 * np.exp(P_4)
        profits_4 = revenue_4 * grmar4_avg
        
        
        ###########
        #  SKU5   # 
        ###########
        
        intercept_5 = np.random.normal(intercept_mu_5, intercept_sigma_5)
        B1_5   = np.random.normal(B1_mu_P2_5, B1_sigma_P2_5)
        B2_5   = np.random.normal(B2_mu_P3_5, B2_sigma_P3_5)   
        B3_5   = np.random.normal(B3_mu_P4_5, B3_sigma_P4_5) 
        B4_5   = np.random.normal(B4_mu_P5_5, B4_sigma_P5_5) 
        feat5  = np.random.randint(2)
        disp5  = np.random.randint(2)
        
        sales_5 = intercept_5 \
                + np.exp(B1_5 * P_2 \
                + B2_5 * P_3 \
                + B3_5 * P_4 \
                + B4_5 * P_5) \
                + B5_mu_D5_5 * disp5 \
                + B6_mu_F5_5 * feat5
        
        revenue_5 = sales_5 * oz_5 * np.exp(P_5)
        profits_5 = revenue_5 * grmar5_avg
        
        
        ####################
        #  Appending SKUs  # 
        ####################
        
        
        all_stats.append([sales_5, revenue_5, profits_5, disp5, feat5, 
                          sales_4, revenue_4, profits_4, disp4, feat4, 
                          sales_3, revenue_3, profits_3, disp3, feat3,
                          sales_2, revenue_2, profits_2, disp2, feat2,
                          sales_1, revenue_1, profits_1, disp1, feat1,])
        
           
    results_df = pd.DataFrame.from_records(all_stats, columns =
    ['units_sold_5','revenue_5','profits_5','disp_5','feat_5',
     'units_sold_4','revenue_4','profits_4','disp_4','feat_4',
     'units_sold_3','revenue_3','profits_3','disp_3','feat_3',
     'units_sold_2','revenue_2','profits_2','disp_2','feat_2',
     'units_sold_1','revenue_1','profits_1','disp_1','feat_1'])
        
    final_stats.append([np.exp(P_5), np.exp(P_4), np.exp(P_3),
                        np.exp(P_2), np.exp(P_1),
                        results_df['profits_5'].mean(),
                        results_df['profits_4'].mean(),
                        results_df['profits_3'].mean(),
                        results_df['profits_2'].mean(),
                        results_df['profits_1'].mean(),
                        results_df['feat_5'].value_counts().idxmax(), # most frequent value
                        results_df['feat_4'].value_counts().idxmax(),
                        results_df['feat_3'].value_counts().idxmax(),
                        results_df['feat_2'].value_counts().idxmax(),
                        results_df['feat_1'].value_counts().idxmax(),
                        results_df['disp_5'].value_counts().idxmax(),
                        results_df['disp_4'].value_counts().idxmax(),
                        results_df['disp_3'].value_counts().idxmax(),
                        results_df['disp_2'].value_counts().idxmax(),
                        results_df['disp_1'].value_counts().idxmax()])
    
final_stats_df = pd.DataFrame.from_records(final_stats, columns =
                ['Price per Oz_5', 'Price per Oz_4',
                 'Price per Oz_3', 'Price per Oz_2', 'Price per Oz_1',
                 'Profits_5', 'Profits_4', 
                 'Profits_3', 'Profits_2', 'Profits_1',
                 'Feat_5', 'Feat_4', 'Feat_3', 'Feat_2', 'Feat_1',
                 'Disp_5', 'Disp_4', 'Disp_3', 'Disp_2', 'Disp_1'])

final_stats_df['Total Profits'] = final_stats_df['Profits_5']\
                                + final_stats_df['Profits_4']\
                                + final_stats_df['Profits_3']\
                                + final_stats_df['Profits_2']\
                                + final_stats_df['Profits_1']


final_stats_df

,Price per Oz_5,Price per Oz_4,Price per Oz_3,Price per Oz_2,Price per Oz_1,Profits_5,Profits_4,Profits_3,Profits_2,Profits_1,Feat_5,Feat_4,Feat_3,Feat_2,Feat_1,Disp_5,Disp_4,Disp_3,Disp_2,Disp_1,Total Profits
0,0.015469,0.020156,0.027656,0.051021,0.032562,6.272302e+05,1.916947e+09,2586.053762,81.726924,1025.658679,0,0,1,0,1,1,0,1,0,1,1.917578e+09
1,0.024844,0.025469,0.023281,0.041729,0.051031,3.237570e+05,2.061242e+08,14013.000623,104.634237,437.342160,1,0,1,0,0,0,0,1,1,1,2.064626e+08
2,0.029531,0.030781,0.036406,0.046375,0.038719,2.160613e+05,9.104328e+07,1692.852700,91.304705,863.608081,1,0,1,1,0,0,0,0,1,0,9.126199e+07
3,0.020156,0.036094,0.040781,0.037083,0.026406,1.075295e+06,2.531146e+08,821.148044,93.963032,1744.792200,0,1,1,0,1,0,1,1,1,0,2.541925e+08
4,0.034219,0.041406,0.032031,0.055667,0.044875,1.066876e+05,2.707860e+07,4435.922968,84.180457,624.784385,1,1,0,0,1,1,1,1,0,1,2.719043e+07

In [22]:
results_df

,units_sold_5,revenue_5,profits_5,disp_5,feat_5,units_sold_4,revenue_4,profits_4,disp_4,feat_4,units_sold_3,revenue_3,profits_3,disp_3,feat_3,units_sold_2,revenue_2,profits_2,disp_2,feat_2,units_sold_1,revenue_1,profits_1,disp_1,feat_1
0,2.943941e+03,6.447230e+03,1888.444523,1,1,2.905008e+05,7.698272e+05,1.950553e+05,0,0,237.050312,485.953139,143.144755,0,1,22.337263,119.370332,34.089375,1,1,116.414284,334.341822,93.391377,0,0
1,7.728915e+04,1.692632e+05,49578.537660,1,0,2.811958e+06,7.451688e+06,1.888074e+06,1,1,144.448657,296.119746,87.226494,0,1,91.598151,489.500521,139.789899,1,0,375.929798,1079.670379,301.583279,0,0
2,2.018434e+03,4.420370e+03,1294.761180,0,1,3.858871e+05,1.022601e+06,2.591019e+05,0,0,775.723708,1590.233600,468.427057,0,1,51.348752,274.407731,78.364429,0,1,221.947946,637.434502,178.053961,0,0
3,1.099326e+03,2.407524e+03,705.182794,1,1,6.198284e+06,1.642545e+07,4.161806e+06,1,1,12901.685712,26448.455709,7790.787633,0,0,24.372907,130.248815,37.196015,0,1,2142.243081,6152.522130,1718.578037,0,0
4,7.596663e+03,1.663669e+04,4873.018562,0,1,2.534744e+06,6.717071e+06,1.701941e+06,1,1,4202.564664,8615.257561,2537.752782,0,0,145.594406,778.056507,222.194739,1,0,1621.019403,4655.567727,1300.435216,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,1.179852e-01,2.583876e-01,0.075684,0,0,2.519999e+08,6.677998e+08,1.692040e+08,1,1,428.023146,877.447449,258.465251,0,0,24.059371,128.573281,36.717522,1,0,459.481599,1319.631154,368.611290,1,1
9996,1.141517e+06,2.499923e+06,732247.122721,1,0,2.965493e+06,7.858556e+06,1.991165e+06,1,1,10873.968450,22291.635322,6566.334106,0,0,14.316905,76.509538,21.849334,0,0,414.611091,1190.763054,332.614689,1,0
9997,3.399854e+02,7.445680e+02,218.089852,0,1,1.309581e+07,3.470390e+07,8.793114e+06,1,0,2182.943124,4475.033405,1318.187923,0,1,30.469382,162.828378,46.499976,1,1,937.322843,2691.991204,751.951291,1,0
9998,1.337098e+02,2.928245e+02,85.770595,0,0,1.237151e+07,3.278451e+07,8.306788e+06,1,0,21862.775281,44818.689326,13202.014301,1,0,29.583880,158.096256,45.148593,1,0,99.886597,286.874306,80.132322,0,1
9999,7.647289e+03,1.674756e+04,4905.493356,0,0,1.560154e+07,4.134409e+07,1.047558e+07,1,1,32.897800,67.440491,19.865604,0,1,25.373140,135.594062,38.722492,1,1,1631.366548,4685.284726,1308.736037,0,0

In [18]:
# Extract price per SKU as log
P_1 = 0.032562
P_2 = 0.051021
P_3 = 0.027656
P_4 = 0.020156
P_5 = 0.015469

number_sims = 10000

final_stats = []

# Placeholder
all_stats = []

# Begin Simulation Loop
for i in range(number_sims):

    ###########
    #  SKU1   # 
    ###########

    intercept_1 = np.random.normal(intercept_mu_1, intercept_sigma_1)
    B1_1   = np.random.normal(B1_mu_P1_1, B1_sigma_P1_1)
    B2_1   = np.random.normal(B2_mu_P3_1, B2_sigma_P3_1)   
    feat1  = np.random.randint(2)
    disp1  = np.random.randint(2)

    sales_1 = intercept_1 \
            + np.exp(B1_1 * P_1 \
            + B2_1 * P_3) \
            + B3_mu_D1_1 * disp1 \
            + B4_mu_F1_1 * feat1
    revenue_1 = sales_1 * oz_1 * np.exp(P_1)
    profits_1 = revenue_1 * grmar1_avg


    ###########
    #  SKU2   # 
    ###########

    intercept_2 = np.random.normal(intercept_mu_2, intercept_sigma_2)
    B1_2   = np.random.normal(B1_mu_P1_2, B1_sigma_P1_2)
    B2_2   = np.random.normal(B2_mu_P2_2, B2_sigma_P2_2)   
    feat2  = np.random.randint(2)
    disp2  = np.random.randint(2)

    sales_2 = intercept_2 \
            + np.exp(B1_2 * P_1 \
            + B2_2 * P_2) \
            + B3_mu_D2_2 * disp2 \
            + B4_mu_F2_2 * feat2

    revenue_2 = sales_2 * oz_2 * np.exp(P_2)
    profits_2 = revenue_2 * grmar2_avg


    ###########
    #  SKU3   # 
    ###########

    intercept_3 = np.random.normal(intercept_mu_3, intercept_sigma_3)
    B1_3   = np.random.normal(B1_mu_P1_3, B1_sigma_P1_3)
    B2_3   = np.random.normal(B2_mu_P3_3, B2_sigma_P3_3)   
    B3_3   = np.random.normal(B3_mu_P4_3, B3_sigma_P4_3) 
    feat3  = np.random.randint(2)
    disp3  = np.random.randint(2)

    sales_3 = intercept_3 \
            + np.exp(B1_3 * P_1 \
            + B2_3 * P_3 \
            + B3_3 * P_4) \
            + B4_mu_D3_3 * disp3 \
            + B5_mu_F3_3 * feat3

    revenue_3 = sales_3 * oz_3 * np.exp(P_3)
    profits_3 = revenue_3 * grmar3_avg


    ###########
    #  SKU4   # 
    ###########

    intercept_4 = np.random.normal(intercept_mu_4, intercept_sigma_4)
    B1_4   = np.random.normal(B1_mu_P1_4, B1_sigma_P1_4)
    B2_4   = np.random.normal(B2_mu_P3_4, B2_sigma_P3_4)   
    B3_4   = np.random.normal(B3_mu_P4_4, B3_sigma_P4_5) 
    B4_4   = np.random.normal(B4_mu_P5_5, B4_sigma_P5_5)
    feat4  = np.random.randint(2)
    disp4  = np.random.randint(2)

    sales_4 = intercept_4 \
            + np.exp(B1_4 * P_1 \
            + B2_4 * P_3 \
            + B3_4 * P_4 \
            + B4_4 * P_5) \
            + B5_mu_D4_4 * disp4 \
            + B6_mu_F4_4 * feat4

    revenue_4 = sales_4 * oz_4 * np.exp(P_4)
    profits_4 = revenue_4 * grmar4_avg


    ###########
    #  SKU5   # 
    ###########

    intercept_5 = np.random.normal(intercept_mu_5, intercept_sigma_5)
    B1_5   = np.random.normal(B1_mu_P2_5, B1_sigma_P2_5)
    B2_5   = np.random.normal(B2_mu_P3_5, B2_sigma_P3_5)   
    B3_5   = np.random.normal(B3_mu_P4_5, B3_sigma_P4_5) 
    B4_5   = np.random.normal(B4_mu_P5_5, B4_sigma_P5_5) 
    feat5  = np.random.randint(2)
    disp5  = np.random.randint(2)

    sales_5 = intercept_5 \
            + np.exp(B1_5 * P_2 \
            + B2_5 * P_3 \
            + B3_5 * P_4 \
            + B4_5 * P_5) \
            + B5_mu_D5_5 * disp5 \
            + B6_mu_F5_5 * feat5

    revenue_5 = sales_5 * oz_5 * np.exp(P_5)
    profits_5 = revenue_5 * grmar5_avg


    ####################
    #  Appending SKUs  # 
    ####################


    all_stats.append([sales_5, revenue_5, profits_5, disp5, feat5, 
                      sales_4, revenue_4, profits_4, disp4, feat4, 
                      sales_3, revenue_3, profits_3, disp3, feat3,
                      sales_2, revenue_2, profits_2, disp2, feat2,
                      sales_1, revenue_1, profits_1, disp1, feat1,])


results_df = pd.DataFrame.from_records(all_stats, columns =
['units_sold_5','revenue_5','profits_5','disp_5','feat_5',
 'units_sold_4','revenue_4','profits_4','disp_4','feat_4',
 'units_sold_3','revenue_3','profits_3','disp_3','feat_3',
 'units_sold_2','revenue_2','profits_2','disp_2','feat_2',
 'units_sold_1','revenue_1','profits_1','disp_1','feat_1'])

final_stats.append([np.exp(P_5), np.exp(P_4), np.exp(P_3),
                    np.exp(P_2), np.exp(P_1),
                    results_df['profits_5'].mean(),
                    results_df['profits_4'].mean(),
                    results_df['profits_3'].mean(),
                    results_df['profits_2'].mean(),
                    results_df['profits_1'].mean(),
                    results_df['feat_5'].value_counts().idxmax(), # most frequent value
                    results_df['feat_4'].value_counts().idxmax(),
                    results_df['feat_3'].value_counts().idxmax(),
                    results_df['feat_2'].value_counts().idxmax(),
                    results_df['feat_1'].value_counts().idxmax(),
                    results_df['disp_5'].value_counts().idxmax(),
                    results_df['disp_4'].value_counts().idxmax(),
                    results_df['disp_3'].value_counts().idxmax(),
                    results_df['disp_2'].value_counts().idxmax(),
                    results_df['disp_1'].value_counts().idxmax()])

final_stats_df = pd.DataFrame.from_records(final_stats, columns =
            ['Price per Oz_5', 'Price per Oz_4',
             'Price per Oz_3', 'Price per Oz_2', 'Price per Oz_1',
             'Profits_5', 'Profits_4', 
             'Profits_3', 'Profits_2', 'Profits_1',
             'Feat_5', 'Feat_4', 'Feat_3', 'Feat_2', 'Feat_1',
             'Disp_5', 'Disp_4', 'Disp_3', 'Disp_2', 'Disp_1'])

final_stats_df['Total Profits'] = final_stats_df['Profits_5']\
                            + final_stats_df['Profits_4']\
                            + final_stats_df['Profits_3']\
                            + final_stats_df['Profits_2']\
                            + final_stats_df['Profits_1']


final_stats_df

,Price per Oz_5,Price per Oz_4,Price per Oz_3,Price per Oz_2,Price per Oz_1,Profits_5,Profits_4,Profits_3,Profits_2,Profits_1,Feat_5,Feat_4,Feat_3,Feat_2,Feat_1,Disp_5,Disp_4,Disp_3,Disp_2,Disp_1,Total Profits
0,1.015589,1.020361,1.028042,1.052345,1.033098,13.840449,123.104859,88.018677,189.022563,79.668436,1,1,0,1,0,0,0,0,0,1,493.654983